### ISSUE TITLE
Tracking: Revise Pay-as-clear market

### ISSUE THREAD

**Issue by j-ti** [BESTenergytrade/simply#197]
PRs:
- [ ] PAC Market Maker #153 
- [x] PAC using grid fees #159
  - [x] resolving Issues #158 and #154
  - [x] Doc update #152
